apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vote-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: 'https://github.com/suchithra05/argo-manifests.git'
    targetRevision: main
    path: helm-packages
    helm:
      releaseName: vote-app
      valueFiles:
        - values.yaml   

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default

  syncPolicy:
    automated:          
      prune: true
      selfHeal: true
