apiVersion: v1
kind: Service
metadata:
  name: voting-app-active
spec:
  selector:
    app: voting-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: voting-app-preview
spec:
  selector:
    app: voting-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
