apiVersion: v1
kind: Service
metadata:
  name: voting-app-active
spec:
  type: NodePort
  selector:
    app: voting-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080  

---
apiVersion: v1
kind: Service
metadata:
  name: voting-app-preview
spec:
  type: NodePort
  selector:
    app: voting-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30081  
