apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: voting-app
  labels:
    app: voting-app
spec:
  replicas: 2
  strategy:
    blueGreen:
      activeService: voting-app-active
      previewService: voting-app-preview
      autoPromotionEnabled: false
  selector:
    matchLabels:
      app: voting-app
  template:
    metadata:
      labels:
        app: voting-app
    spec:
      containers:
        - name: voting-app
          image: suchithra05/voting-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: voting-app-config
                  key: REDIS_HOST
            - name: APP_TITLE
              valueFrom:
                configMapKeyRef:
                  name: voting-app-config
                  key: APP_TITLE
